# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0008_hashtag_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
