# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 03:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.AddField(
            model_name='user',
            name='date_accessed',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 27, 3, 5, 15, 185121, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
