# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0015_auto_20160327_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_accessed',
            name='user',
        ),
        migrations.DeleteModel(
            name='page_accessed',
        ),
    ]
