# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0017_user_page_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_page_accessed',
            name='page',
        ),
        migrations.AddField(
            model_name='user_page_accessed',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
