# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0021_auto_20160329_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_page_accessed',
            options={'ordering': ['-date_accessed']},
        ),
    ]
