# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0022_auto_20160329_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiblog.User'),
        ),
    ]
