# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(max_length=255)),
                ('file_obj', models.FileField(upload_to='uploaded_files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bodytext', models.CharField(max_length=40000)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiblog.Page'),
        ),
    ]
