# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0005_auto_20160317_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='hashtag',
        ),
    ]
