# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0010_auto_20160318_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['tag']},
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 22, 5, 8, 48, 679457, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
