# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0018_auto_20160329_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_page_accessed',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
