# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0020_user_page_accessed_user_page_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_page_accessed',
            options={'ordering': ['date_accessed']},
        ),
        migrations.RemoveField(
            model_name='user_page_accessed',
            name='user_page_from',
        ),
        migrations.AddField(
            model_name='user_page_accessed',
            name='referring_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
