# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiblog', '0024_auto_20160403_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='page',
            name='bodytext',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
    ]
